version: 0.1

phases:
  pre_build:
    commands:
      - pip install docker
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - pip install docker-compose
  build:
    commands:
      - docker build -t $APP_IMAGE .
      - COMPOSE_HTTP_TIMEOUT=200 docker-compose run --rm test
      - docker push $APP_IMAGE
  post_build:
    commands:
      - echo Build completed on `date`